"use client"

import type React from "react"
import { createContext, useContext, useEffect, useMemo, useState } from "react"

type Language = "en" | "es"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const LANGUAGE_STORAGE_KEY = "serviscore-language"
const LANGUAGE_EVENT_NAME = "serviscore-language-change"

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.profile": "Profile",
    "nav.login": "Login",
    "home.hero.title": "Discover & Connect",
    "home.hero.subtitle":
      "Your community hub for finding the best local businesses and connecting with skilled neighbors.",
    "home.services.title": "Community Services",
    "services.title": "Community Services",
    "services.subtitle": "Find help or offer your skills to neighbors.",
    "services.filter": "Filter",
    "services.fixedPrice": "Fixed Price",
    "services.status.open": "Open",
    "services.post.button": "Post Service",
    "services.post.title": "Post a Service",
    "services.post.description": "Offer your skills to the community. Fill in the details below.",
    "services.post.serviceTitle": "Service Title",
    "services.post.serviceTitlePlaceholder": "e.g. Dog Walking, House Cleaning",
    "services.post.category": "Category",
    "services.post.categoryPlaceholder": "Select",
    "services.post.category.home": "Home",
    "services.post.category.pets": "Pets",
    "services.post.category.tech": "Tech",
    "services.post.category.education": "Education",
    "services.post.price": "Price ($)",
    "services.post.location": "Location",
    "services.post.locationPlaceholder": "e.g. Downtown, Westside",
    "services.post.descriptionLabel": "Description",
    "services.post.descriptionPlaceholder": "Describe what you offer...",
    "home.reviews": "reviews",
    "service.back": "Back to Services",
    "service.posted": "Posted on",
    "service.description": "Description",
    "service.applicants": "Applicants",
    "service.noApplicants": "No applicants yet.",
    "service.memberSince": "Member since",
    "service.rating": "Rating",
    "service.jobs": "Jobs",
    "service.viewProfile": "View Profile",
    "service.interested": "Interested?",
    "service.applyHelp": "Apply now to help {name} with this task.",
    "service.applied": "Applied",
    "service.apply": "Apply for Service",
    "service.accept": "Accept",
    "service.decline": "Decline",
    "service.notFound": "Service not found",
    "profile.settings": "Settings",
    "profile.logout": "Logout",
    "profile.completed": "Completed",
    "profile.publishedServices": "Published Services",
    "profile.noServices": "No services published yet.",
    "profile.recentActivity": "Recent Activity",
    "profile.manage": "Manage",
    "profile.active": "Active",
    "common.location": "Location",
    "common.hours": "Hours",
    "common.about": "About",
    "common.loading": "Loading...",
    "auth.welcome": "Welcome back",
    "auth.login.subtitle": "Please enter your details to log in.",
    "auth.createAccount": "Create an account",
    "auth.register.subtitle": "Already have an account?",
    "auth.login": "Log in",
    "auth.signup": "Sign up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.firstName": "First name",
    "auth.lastName": "Last name",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.orLogin": "Or log in with",
    "auth.orRegister": "Or register with",
    "auth.agree": "I agree to the",
    "auth.terms": "Terms & Conditions",
    "auth.google": "Google",
    "auth.apple": "Apple",
    "auth.overlay.title": "Capturing Moments, Creating Memories",
    "auth.overlay.subtitle": "Start your journey with us today.",
    "auth.backToWebsite": "Back to website",
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back! Here's your business overview.",
    "dashboard.newStore": "New Store",
    "dashboard.newService": "New Service",
    "dashboard.totalStores": "Total Stores",
    "dashboard.activeServices": "Active Services",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.totalCustomers": "Total Customers",
    "dashboard.fromLastMonth": "from last month",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.recentActivityDesc": "Latest updates across your stores and services",
    "dashboard.topPerformers": "Top Performers",
    "dashboard.topPerformersDesc": "Highest performing stores this month",
    "dashboard.newOrderReceived": "New order received",
    "dashboard.serviceCompleted": "Service completed",
    "dashboard.newReviewPosted": "New review posted",
    "dashboard.inventoryUpdated": "Inventory updated",
    "dashboard.revenue": "revenue",
    "landing.nav.features": "Features",
    "landing.nav.benefits": "Benefits",
    "landing.nav.about": "About",
    "landing.nav.testimonials": "Testimonials",
    "landing.nav.getStarted": "Get Started",
    "landing.hero.subtitle": "The Community Marketplace That Connects Local Talent",
    "landing.hero.description": "Discover skilled professionals in your neighborhood. From home services to tech support, find trusted providers or offer your expertise to earn extra income.",
    "landing.hero.getStarted": "Start Now - It's Free",
    "landing.hero.learnMore": "How It Works",
    "landing.hero.stats.users": "Active Users",
    "landing.hero.stats.services": "Services Posted",
    "landing.hero.stats.rating": "Average Rating",
    "landing.features.title": "Everything You Need in One Platform",
    "landing.features.subtitle": "Built for the modern community marketplace. Simple, powerful, and designed to help you succeed.",
    "landing.features.verified": "Verified Profiles",
    "landing.features.verifiedDesc": "Trust matters. All service providers go through our verification process with ratings and reviews from real customers.",
    "landing.features.instant": "Instant Booking",
    "landing.features.instantDesc": "Book services in seconds. Real-time availability, instant confirmations, and secure in-app messaging.",
    "landing.features.payment": "Secure Payments",
    "landing.features.paymentDesc": "Pay with confidence. Escrow protection ensures payment is only released when you're 100% satisfied.",
    "landing.features.local": "Local First",
    "landing.features.localDesc": "Support your community. Find services near you with GPS-based search and neighborhood filters.",
    "landing.features.ratings": "Transparent Ratings",
    "landing.features.ratingsDesc": "Make informed decisions. Detailed reviews, photos, and performance metrics for every provider.",
    "landing.features.support": "24/7 Support",
    "landing.features.supportDesc": "We've got your back. AI-powered chatbot and human support team ready to help anytime.",
    "landing.benefits.title": "Why Thousands Choose ServiScore",
    "landing.benefits.subtitle": "Whether you're looking for help or offering your skills, ServiScore is the smartest way to connect with your community.",
    "landing.benefits.forCustomers": "For Customers",
    "landing.benefits.save": "Save up to 40% compared to traditional services",
    "landing.benefits.fast": "Get help fast - average response time under 2 hours",
    "landing.benefits.trust": "Book with confidence using verified profiles and reviews",
    "landing.benefits.forProviders": "For Service Providers",
    "landing.benefits.earn": "Earn extra income on your schedule",
    "landing.benefits.grow": "Build your reputation with every 5-star review",
    "landing.benefits.tools": "Professional tools at your fingertips - no expensive software needed",
    "landing.benefits.stat1": "95%",
    "landing.benefits.stat1Label": "Customer Satisfaction Rate",
    "landing.benefits.stat2": "10K+",
    "landing.benefits.stat2Label": "Services Completed Monthly",
    "landing.benefits.stat3": "4.8★",
    "landing.benefits.stat3Label": "Average Provider Rating",
    "landing.testimonials.title": "Loved by Our Community",
    "landing.testimonials.subtitle": "Real stories from real people in your neighborhood.",
    "landing.testimonials.quote1": "Found a great plumber in my area within minutes! The booking process was seamless and the quality was excellent.",
    "landing.testimonials.quote2": "As a freelance designer, ServiScore has connected me with amazing local clients. Best decision for my side hustle!",
    "landing.testimonials.quote3": "The verification process gives me peace of mind. I know I'm hiring trustworthy people from my community.",
    "landing.cta.title": "Ready to Join Your Local Community?",
    "landing.cta.subtitle": "Join thousands of neighbors helping neighbors. Whether you need a service or want to offer one, get started in less than 2 minutes.",
    "landing.cta.getStarted": "Create Free Account",
    "landing.cta.requestDemo": "Browse Services",
    "landing.cta.noCredit": "No credit card required",
    "landing.about.title": "Built for Communities, By Communities",
    "landing.about.subtitle": "ServiScore was born from a simple idea: neighbors helping neighbors should be easy, safe, and rewarding.",
    "landing.about.mission": "Our Mission",
    "landing.about.missionDesc": "To create the most trusted platform for local service exchange, empowering communities to thrive together.",
    "landing.about.vision": "Our Vision",
    "landing.about.visionDesc": "A world where every neighborhood is a connected community of skilled individuals ready to help each other.",
    "authForm.signIn": "Sign In",
    "authForm.signUp": "Sign Up",
    "authForm.signInSubtitle": "Enter your email and password to sign in!",
    "authForm.signUpSubtitle": "Enter your email and password to sign up!",
    "authForm.signInWith": "Sign in with",
    "authForm.signUpWith": "Sign up with",
    "authForm.or": "Or",
    "authForm.enterPassword": "Enter your password",
    "authForm.enterEmail": "Enter your email",
    "authForm.enterFirstName": "Enter your first name",
    "authForm.enterLastName": "Enter your last name",
    "authForm.keepLoggedIn": "Keep me logged in",
    "authForm.resetPassword": "Forgot password?",
    "authForm.dontHaveAccount": "Don't have an account?",
    "authForm.alreadyHaveAccount": "Already have an account?",
    "authForm.byCreating": "By creating an account means you agree to the",
    "authForm.termsConditions": "Terms and Conditions,",
    "authForm.and": "and our",
    "authForm.privacyPolicy": "Privacy Policy",
    "authForm.backToDashboard": "Back to dashboard",
    "sidebar.platform": "Platform",
    "sidebar.home": "Home",
    "sidebar.dashboard": "Dashboard",
    "sidebar.profile": "Profile",
    "sidebar.management": "Management",
    "sidebar.manageShops": "Manage Shops",
    "sidebar.manageServices": "Manage Services",
    "sidebar.team": "Team",
    "sidebar.analytics": "Analytics",
    "sidebar.shopAnalytics": "Shop Analytics",
    "sidebar.shopMetrics": "Shop Metrics",
    "sidebar.serviceMetrics": "Service Metrics",
    "sidebar.systemLogs": "System Logs",
    "sidebar.explore": "Explore",
    "sidebar.browseStores": "Browse Stores",
    "sidebar.browseServices": "Browse Services",
    "sidebar.admin": "Admin",
    "sidebar.superProfile": "Super Profile",
    "sidebar.settings": "Settings",
    "sidebar.getHelp": "Get Help",
    "sidebar.search": "Search",
    "sidebar.searchPlaceholder": "Search pages and commands...",
    "about.title": "Built for",
    "about.titleHighlight": "Growth",
    "about.subtitle": "Everything you need to manage, scale, and succeed in one powerful platform.",
    "about.globalReach": "Global Reach",
    "about.globalReachDesc": "Expand your business beyond borders with our integrated SEO and localization tools.",
    "about.advancedAnalytics": "Advanced Analytics",
    "about.advancedAnalyticsDesc": "Gain deep insights into your audience and performance with real-time data visualization.",
    "about.designIntelligence": "Design Intelligence",
    "about.designIntelligenceDesc": "Create stunning, professional visuals effortlessly with our AI-powered design assistant.",
    "about.secureReliable": "Secure & Reliable",
    "about.secureReliableDesc": "Rest easy knowing your data and your customers' information are protected by enterprise-grade security.",
    "about.communityDriven": "Community Driven",
    "about.communityDrivenDesc": "Connect with a vibrant network of professionals and customers in your local area.",
    "about.lightningFast": "Lightning Fast",
    "about.lightningFastDesc": "Experience optimized performance that keeps your customers engaged and converting.",
    "footer.description": "Connecting neighbors, building trust, and making local services accessible to everyone.",
    "footer.product": "Product",
    "footer.howItWorks": "How It Works",
    "footer.categories": "Service Categories",
    "footer.becomeProvider": "Become a Provider",
    "footer.company": "Company",
    "footer.blog": "Blog",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.support": "Support",
    "footer.helpCenter": "Help Center",
    "footer.safety": "Safety & Trust",
    "footer.community": "Community Guidelines",
    "footer.createdBy": "Created by passionate Riwi team",
    "footer.platform": "Platform",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.aboutUs": "About Us",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",
    "footer.cookiePolicy": "Cookie Policy",
    "footer.allRightsReserved": "All rights reserved.",
    "support.title": "Hi, how can we help?",
    "support.searchPlaceholder": "Search for articles",
    "support.exploreTopics": "Explore all topics",
    "support.sendingMoney": "Sending money",
    "support.sendingMoneyDesc": "Setting up, paying for, editing, and cancelling transfers.",
    "support.managingAccount": "Managing your account",
    "support.managingAccountDesc": "Setting up your account and getting verified.",
    "support.holdingMoney": "Holding money",
    "support.holdingMoneyDesc": "Holding balances, setting up Direct Debits, and using Interest & Stocks.",
    "support.wiseCard": "Wise card",
    "support.wiseCardDesc": "Ordering, activating, spending, and troubleshooting.",
    "support.receivingMoney": "Receiving money",
    "support.receivingMoneyDesc": "Using your account details to receive money.",
    "support.wiseBusiness": "Wise Business",
    "support.wiseBusinessDesc": "Multi-user access, accounting and using our API.",
    "support.stillNeedHelp": "Still need help?",
    "support.contactUs": "Contact us",
  },
  es: {
    "nav.home": "Inicio",
    "nav.services": "Servicios",
    "nav.profile": "Perfil",
    "nav.login": "Iniciar Sesión",
    "home.hero.title": "Descubre y Conecta",
    "home.hero.subtitle":
      "Tu centro comunitario para encontrar los mejores negocios locales y conectar con vecinos talentosos.",
    "home.services.title": "Servicios Comunitarios",
    "services.title": "Servicios Comunitarios",
    "services.subtitle": "Encuentra ayuda u ofrece tus habilidades a tus vecinos.",
    "services.filter": "Filtrar",
    "services.fixedPrice": "Precio fijo",
    "services.status.open": "Abierto",
    "services.post.button": "Publicar servicio",
    "services.post.title": "Publicar un servicio",
    "services.post.description": "Ofrece tus habilidades a la comunidad. Completa los detalles a continuación.",
    "services.post.serviceTitle": "Título del servicio",
    "services.post.serviceTitlePlaceholder": "Ej. Paseo de perros, Limpieza del hogar",
    "services.post.category": "Categoría",
    "services.post.categoryPlaceholder": "Seleccionar",
    "services.post.category.home": "Hogar",
    "services.post.category.pets": "Mascotas",
    "services.post.category.tech": "Tecnología",
    "services.post.category.education": "Educación",
    "services.post.price": "Precio ($)",
    "services.post.location": "Ubicación",
    "services.post.locationPlaceholder": "Ej. Centro, Zona oeste",
    "services.post.descriptionLabel": "Descripción",
    "services.post.descriptionPlaceholder": "Describe lo que ofreces...",
    "home.reviews": "reseñas",
    "service.back": "Volver a Servicios",
    "service.posted": "Publicado el",
    "service.description": "Descripción",
    "service.applicants": "Solicitantes",
    "service.noApplicants": "Aún no hay solicitantes.",
    "service.memberSince": "Miembro desde",
    "service.rating": "Calif.",
    "service.jobs": "Trabajos",
    "service.viewProfile": "Ver Perfil",
    "service.interested": "¿Interesado?",
    "service.applyHelp": "Aplica ahora para ayudar a {name} con esta tarea.",
    "service.applied": "Aplicado",
    "service.apply": "Aplicar al Servicio",
    "service.accept": "Aceptar",
    "service.decline": "Rechazar",
    "service.notFound": "Servicio no encontrado",
    "profile.settings": "Ajustes",
    "profile.logout": "Cerrar Sesión",
    "profile.completed": "Completados",
    "profile.publishedServices": "Servicios Publicados",
    "profile.noServices": "Aún no hay servicios publicados.",
    "profile.recentActivity": "Actividad Reciente",
    "profile.manage": "Gestionar",
    "profile.active": "Activo",
    "common.location": "Ubicación",
    "common.hours": "Horario",
    "common.about": "Sobre nosotros",
    "common.loading": "Cargando...",
    "auth.welcome": "Bienvenido de nuevo",
    "auth.login.subtitle": "Por favor ingrese sus detalles para iniciar sesión.",
    "auth.createAccount": "Crear una cuenta",
    "auth.register.subtitle": "¿Ya tienes una cuenta?",
    "auth.login": "Iniciar sesión",
    "auth.signup": "Registrarse",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.firstName": "Nombre",
    "auth.lastName": "Apellido",
    "auth.rememberMe": "Recuérdame",
    "auth.forgotPassword": "¿Olvidaste tu contraseña?",
    "auth.orLogin": "O iniciar sesión con",
    "auth.orRegister": "O registrarse con",
    "auth.agree": "Acepto los",
    "auth.terms": "Términos y Condiciones",
    "auth.google": "Google",
    "auth.apple": "Apple",
    "auth.overlay.title": "Capturando Momentos, Creando Recuerdos",
    "auth.overlay.subtitle": "Comienza tu viaje con nosotros hoy.",
    "auth.backToWebsite": "Volver al sitio web",
    "dashboard.title": "Panel de Control",
    "dashboard.welcome": "¡Bienvenido de nuevo! Aquí está el resumen de tu negocio.",
    "dashboard.newStore": "Nueva Tienda",
    "dashboard.newService": "Nuevo Servicio",
    "dashboard.totalStores": "Tiendas Totales",
    "dashboard.activeServices": "Servicios Activos",
    "dashboard.totalRevenue": "Ingresos Totales",
    "dashboard.totalCustomers": "Clientes Totales",
    "dashboard.fromLastMonth": "del mes pasado",
    "dashboard.recentActivity": "Actividad Reciente",
    "dashboard.recentActivityDesc": "Últimas actualizaciones de tus tiendas y servicios",
    "dashboard.topPerformers": "Mejores Desempeños",
    "dashboard.topPerformersDesc": "Tiendas con mejor desempeño este mes",
    "dashboard.newOrderReceived": "Nuevo pedido recibido",
    "dashboard.serviceCompleted": "Servicio completado",
    "dashboard.newReviewPosted": "Nueva reseña publicada",
    "dashboard.inventoryUpdated": "Inventario actualizado",
    "dashboard.revenue": "ingresos",
    "landing.nav.features": "Características",
    "landing.nav.benefits": "Beneficios",
    "landing.nav.about": "Acerca de",
    "landing.nav.testimonials": "Testimonios",
    "landing.nav.getStarted": "Comenzar",
    "landing.hero.subtitle": "El Marketplace Comunitario Que Conecta Talento Local",
    "landing.hero.description": "Descubre profesionales calificados en tu vecindario. Desde servicios del hogar hasta soporte técnico, encuentra proveedores confiables u ofrece tu experiencia para ganar ingresos extra.",
    "landing.hero.getStarted": "Comenzar Ahora - Es Gratis",
    "landing.hero.learnMore": "Cómo Funciona",
    "landing.hero.stats.users": "Usuarios Activos",
    "landing.hero.stats.services": "Servicios Publicados",
    "landing.hero.stats.rating": "Calificación Promedio",
    "landing.features.title": "Todo Lo Que Necesitas en Una Plataforma",
    "landing.features.subtitle": "Construido para el marketplace comunitario moderno. Simple, poderoso y diseñado para ayudarte a tener éxito.",
    "landing.features.verified": "Perfiles Verificados",
    "landing.features.verifiedDesc": "La confianza importa. Todos los proveedores pasan por nuestro proceso de verificación con calificaciones y reseñas de clientes reales.",
    "landing.features.instant": "Reserva Instantánea",
    "landing.features.instantDesc": "Reserva servicios en segundos. Disponibilidad en tiempo real, confirmaciones instantáneas y mensajería segura en la app.",
    "landing.features.payment": "Pagos Seguros",
    "landing.features.paymentDesc": "Paga con confianza. Protección de depósito garantiza que el pago solo se libera cuando estás 100% satisfecho.",
    "landing.features.local": "Local Primero",
    "landing.features.localDesc": "Apoya tu comunidad. Encuentra servicios cerca de ti con búsqueda basada en GPS y filtros de vecindario.",
    "landing.features.ratings": "Calificaciones Transparentes",
    "landing.features.ratingsDesc": "Toma decisiones informadas. Reseñas detalladas, fotos y métricas de desempeño para cada proveedor.",
    "landing.features.support": "Soporte 24/7",
    "landing.features.supportDesc": "Estamos contigo. Chatbot con IA y equipo de soporte humano listo para ayudar en cualquier momento.",
    "landing.benefits.title": "Por Qué Miles Eligen ServiScore",
    "landing.benefits.subtitle": "Ya sea que busques ayuda u ofrezcas tus habilidades, ServiScore es la forma más inteligente de conectar con tu comunidad.",
    "landing.benefits.forCustomers": "Para Clientes",
    "landing.benefits.save": "Ahorra hasta 40% comparado con servicios tradicionales",
    "landing.benefits.fast": "Obtén ayuda rápido - tiempo de respuesta promedio bajo 2 horas",
    "landing.benefits.trust": "Reserva con confianza usando perfiles verificados y reseñas",
    "landing.benefits.forProviders": "Para Proveedores de Servicio",
    "landing.benefits.earn": "Gana ingresos extra en tu horario",
    "landing.benefits.grow": "Construye tu reputación con cada reseña de 5 estrellas",
    "landing.benefits.tools": "Herramientas profesionales a tu alcance - no necesitas software costoso",
    "landing.benefits.stat1": "95%",
    "landing.benefits.stat1Label": "Tasa de Satisfacción del Cliente",
    "landing.benefits.stat2": "10K+",
    "landing.benefits.stat2Label": "Servicios Completados Mensualmente",
    "landing.benefits.stat3": "4.8★",
    "landing.benefits.stat3Label": "Calificación Promedio de Proveedores",
    "landing.testimonials.title": "Amado por Nuestra Comunidad",
    "landing.testimonials.subtitle": "Historias reales de personas reales en tu vecindario.",
    "landing.testimonials.quote1": "¡Encontré un gran plomero en mi área en minutos! El proceso de reserva fue perfecto y la calidad fue excelente.",
    "landing.testimonials.quote2": "Como diseñadora freelance, ServiScore me ha conectado con increíbles clientes locales. ¡La mejor decisión para mi trabajo extra!",
    "landing.testimonials.quote3": "El proceso de verificación me da tranquilidad. Sé que estoy contratando personas confiables de mi comunidad.",
    "landing.cta.title": "¿Listo para Unirte a Tu Comunidad Local?",
    "landing.cta.subtitle": "Únete a miles de vecinos ayudando a vecinos. Ya sea que necesites un servicio o quieras ofrecer uno, comienza en menos de 2 minutos.",
    "landing.cta.getStarted": "Crear Cuenta Gratis",
    "landing.cta.requestDemo": "Explorar Servicios",
    "landing.cta.noCredit": "No se requiere tarjeta de crédito",
    "landing.about.title": "Construido para Comunidades, Por Comunidades",
    "landing.about.subtitle": "ServiScore nació de una idea simple: vecinos ayudando a vecinos debería ser fácil, seguro y gratificante.",
    "landing.about.mission": "Nuestra Misión",
    "landing.about.missionDesc": "Crear la plataforma más confiable para el intercambio de servicios locales, empoderando a las comunidades para prosperar juntas.",
    "landing.about.vision": "Nuestra Visión",
    "landing.about.visionDesc": "Un mundo donde cada vecindario es una comunidad conectada de individuos capacitados listos para ayudarse mutuamente.",
    "authForm.signIn": "Iniciar Sesión",
    "authForm.signUp": "Registrarse",
    "authForm.signInSubtitle": "¡Ingresa tu correo y contraseña para iniciar sesión!",
    "authForm.signUpSubtitle": "¡Ingresa tu correo y contraseña para registrarte!",
    "authForm.signInWith": "Iniciar sesión con",
    "authForm.signUpWith": "Registrarse con",
    "authForm.or": "O",
    "authForm.enterPassword": "Ingresa tu contraseña",
    "authForm.enterEmail": "Ingresa tu correo",
    "authForm.enterFirstName": "Ingresa tu nombre",
    "authForm.enterLastName": "Ingresa tu apellido",
    "authForm.keepLoggedIn": "Mantenerme conectado",
    "authForm.resetPassword": "¿Olvidaste tu contraseña?",
    "authForm.dontHaveAccount": "¿No tienes una cuenta?",
    "authForm.alreadyHaveAccount": "¿Ya tienes una cuenta?",
    "authForm.byCreating": "Al crear una cuenta aceptas los",
    "authForm.termsConditions": "Términos y Condiciones,",
    "authForm.and": "y nuestra",
    "authForm.privacyPolicy": "Política de Privacidad",
    "authForm.backToDashboard": "Volver al panel",
    "sidebar.platform": "Plataforma",
    "sidebar.home": "Inicio",
    "sidebar.dashboard": "Panel",
    "sidebar.profile": "Perfil",
    "sidebar.management": "Gestión",
    "sidebar.manageShops": "Gestionar Tiendas",
    "sidebar.manageServices": "Gestionar Servicios",
    "sidebar.team": "Equipo",
    "sidebar.analytics": "Analíticas",
    "sidebar.shopAnalytics": "Análisis de Tiendas",
    "sidebar.shopMetrics": "Métricas de Tiendas",
    "sidebar.serviceMetrics": "Métricas de Servicios",
    "sidebar.systemLogs": "Registros del Sistema",
    "sidebar.explore": "Explorar",
    "sidebar.browseStores": "Explorar Tiendas",
    "sidebar.browseServices": "Explorar Servicios",
    "sidebar.admin": "Administrador",
    "sidebar.superProfile": "Super Perfil",
    "sidebar.settings": "Configuración",
    "sidebar.getHelp": "Obtener Ayuda",
    "sidebar.search": "Buscar",
    "sidebar.searchPlaceholder": "Buscar páginas y comandos...",
    "about.title": "Construido para",
    "about.titleHighlight": "Crecer",
    "about.subtitle": "Todo lo que necesitas para gestionar, escalar y tener éxito en una poderosa plataforma.",
    "about.globalReach": "Alcance Global",
    "about.globalReachDesc": "Expande tu negocio más allá de las fronteras con nuestras herramientas integradas de SEO y localización.",
    "about.advancedAnalytics": "Análisis Avanzados",
    "about.advancedAnalyticsDesc": "Obtén información profunda sobre tu audiencia y rendimiento con visualización de datos en tiempo real.",
    "about.designIntelligence": "Inteligencia de Diseño",
    "about.designIntelligenceDesc": "Crea visuales impresionantes y profesionales sin esfuerzo con nuestro asistente de diseño impulsado por IA.",
    "about.secureReliable": "Seguro y Confiable",
    "about.secureReliableDesc": "Descansa tranquilo sabiendo que tus datos y la información de tus clientes están protegidos por seguridad de nivel empresarial.",
    "about.communityDriven": "Impulsado por la Comunidad",
    "about.communityDrivenDesc": "Conéctate con una red vibrante de profesionales y clientes en tu área local.",
    "about.lightningFast": "Súper Rápido",
    "about.lightningFastDesc": "Experimenta un rendimiento optimizado que mantiene a tus clientes comprometidos y convirtiendo.",
    "footer.description": "Empoderando negocios locales y conectando comunidades a través de soluciones digitales innovadoras.",
    "footer.createdBy": "Creado por equipo apasionado de Riwi",
    "footer.platform": "Plataforma",
    "footer.features": "Características",
    "footer.pricing": "Precios",
    "footer.aboutUs": "Sobre Nosotros",
    "footer.contact": "Contacto",
    "footer.legal": "Legal",
    "footer.privacyPolicy": "Política de Privacidad",
    "footer.termsOfService": "Términos de Servicio",
    "footer.cookiePolicy": "Política de Cookies",
    "footer.allRightsReserved": "Todos los derechos reservados.",
    "support.title": "Hola, ¿cómo podemos ayudarte?",
    "support.searchPlaceholder": "Buscar artículos",
    "support.exploreTopics": "Explorar todos los temas",
    "support.sendingMoney": "Enviar dinero",
    "support.sendingMoneyDesc": "Configuración, pago, edición y cancelación de transferencias.",
    "support.managingAccount": "Gestionar tu cuenta",
    "support.managingAccountDesc": "Configurar tu cuenta y verificarte.",
    "support.holdingMoney": "Mantener dinero",
    "support.holdingMoneyDesc": "Mantener saldos, configurar débitos directos y usar Intereses y Acciones.",
    "support.wiseCard": "Tarjeta Wise",
    "support.wiseCardDesc": "Pedido, activación, gasto y solución de problemas.",
    "support.receivingMoney": "Recibir dinero",
    "support.receivingMoneyDesc": "Usar los detalles de tu cuenta para recibir dinero.",
    "support.wiseBusiness": "Wise Business",
    "support.wiseBusinessDesc": "Acceso multiusuario, contabilidad y uso de nuestra API.",
    "support.stillNeedHelp": "¿Aún necesitas ayuda?",
    "support.contactUs": "Contáctanos",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en"
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY)
    return stored === "es" || stored === "en" ? stored : "en"
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, lang)
      window.dispatchEvent(new Event(LANGUAGE_EVENT_NAME))
    } catch {
      // ignore
    }
  }

  useEffect(() => {
    const handler = () => {
      try {
        const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY)
        if (stored === "es" || stored === "en") setLanguageState(stored)
      } catch {
        // ignore
      }
    }

    window.addEventListener(LANGUAGE_EVENT_NAME, handler)
    return () => window.removeEventListener(LANGUAGE_EVENT_NAME, handler)
  }, [])

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key] || key
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(`{${paramKey}}`, String(value))
      })
    }
    return text
  }

  const value = useMemo(() => ({ language, setLanguage, t }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
