"use client"

import type React from "react"
import { createContext, useContext, useEffect, useMemo, useState } from "react"

type Language = "en" | "es"

type LanguageContextType = {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const LANGUAGE_STORAGE_KEY = "serviscore-language"
const LANGUAGE_EVENT_NAME = "serviscore-language-change"

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.profile": "Profile",
    "nav.login": "Login",
    "home.hero.title": "Discover & Connect",
    "home.hero.subtitle":
      "Your community hub for finding the best local businesses and connecting with skilled neighbors.",
    "home.services.title": "Community Services",
    "services.title": "Community Services",
    "services.subtitle": "Find help or offer your skills to neighbors.",
    "services.filter": "Filter",
    "services.fixedPrice": "Fixed Price",
    "services.status.open": "Open",
    "services.post.button": "Post Service",
    "services.post.title": "Post a Service",
    "services.post.description": "Offer your skills to the community. Fill in the details below.",
    "services.post.serviceTitle": "Service Title",
    "services.post.serviceTitlePlaceholder": "e.g. Dog Walking, House Cleaning",
    "services.post.category": "Category",
    "services.post.categoryPlaceholder": "Select",
    "services.post.category.home": "Home",
    "services.post.category.pets": "Pets",
    "services.post.category.tech": "Tech",
    "services.post.category.education": "Education",
    "services.post.price": "Price ($)",
    "services.post.location": "Location",
    "services.post.locationPlaceholder": "e.g. Downtown, Westside",
    "services.post.descriptionLabel": "Description",
    "services.post.descriptionPlaceholder": "Describe what you offer...",
    "home.reviews": "reviews",
    "service.back": "Back to Services",
    "service.posted": "Posted on",
    "service.description": "Description",
    "service.applicants": "Applicants",
    "service.noApplicants": "No applicants yet.",
    "service.memberSince": "Member since",
    "service.rating": "Rating",
    "service.jobs": "Jobs",
    "service.viewProfile": "View Profile",
    "service.interested": "Interested?",
    "service.applyHelp": "Apply now to help {name} with this task.",
    "service.applied": "Applied",
    "service.apply": "Apply for Service",
    "service.accept": "Accept",
    "service.decline": "Decline",
    "service.notFound": "Service not found",
    "profile.settings": "Settings",
    "profile.logout": "Logout",
    "profile.completed": "Completed",
    "profile.publishedServices": "Published Services",
    "profile.noServices": "No services published yet.",
    "profile.recentActivity": "Recent Activity",
    "profile.manage": "Manage",
    "profile.active": "Active",
    "common.location": "Location",
    "common.hours": "Hours",
    "common.about": "About",
    "common.loading": "Loading...",
    "auth.welcome": "Welcome back",
    "auth.login.subtitle": "Please enter your details to log in.",
    "auth.createAccount": "Create an account",
    "auth.register.subtitle": "Already have an account?",
    "auth.login": "Log in",
    "auth.signup": "Sign up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.firstName": "First name",
    "auth.lastName": "Last name",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.orLogin": "Or log in with",
    "auth.orRegister": "Or register with",
    "auth.agree": "I agree to the",
    "auth.terms": "Terms & Conditions",
    "auth.google": "Google",
    "auth.apple": "Apple",
    "auth.overlay.title": "Capturing Moments, Creating Memories",
    "auth.overlay.subtitle": "Start your journey with us today.",
    "auth.backToWebsite": "Back to website",
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back! Here's your business overview.",
    "dashboard.newStore": "New Store",
    "dashboard.newService": "New Service",
    "dashboard.totalStores": "Total Stores",
    "dashboard.activeServices": "Active Services",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.totalCustomers": "Total Customers",
    "dashboard.fromLastMonth": "from last month",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.recentActivityDesc": "Latest updates across your stores and services",
    "dashboard.topPerformers": "Top Performers",
    "dashboard.topPerformersDesc": "Highest performing stores this month",
    "dashboard.newOrderReceived": "New order received",
    "dashboard.serviceCompleted": "Service completed",
    "dashboard.newReviewPosted": "New review posted",
    "dashboard.inventoryUpdated": "Inventory updated",
    "dashboard.revenue": "revenue",
    "landing.hero.subtitle": "Welcome to the future of service",
    "landing.hero.description": "Connect, collaborate, and grow with ServiScore. We provide the tools you need to elevate your business and reach your community effectively.",
    "landing.hero.getStarted": "Get Started",
    "landing.hero.learnMore": "Learn More",
    "landing.features.title": "Key Features",
    "landing.features.subtitle": "Everything you need to elevate your service quality and customer satisfaction.",
    "landing.features.chatbot": "Chatbot Integration",
    "landing.features.chatbotDesc": "Automate customer support with our intelligent AI chatbot that handles common queries 24/7.",
    "landing.features.analytics": "Analytics Dashboard",
    "landing.features.analyticsDesc": "Gain deep insights into your service performance with real-time metrics and visual reports.",
    "landing.features.ui": "User-Friendly Interface",
    "landing.features.uiDesc": "Intuitive design that requires no training. Get your team up and running in minutes.",
    "landing.features.feedback": "Instant Feedback",
    "landing.features.feedbackDesc": "Collect and analyze customer feedback immediately after service completion.",
    "landing.features.security": "Secure Data",
    "landing.features.securityDesc": "Enterprise-grade security to keep your customer and business data safe and compliant.",
    "landing.features.team": "Team Management",
    "landing.features.teamDesc": "Easily manage roles, permissions, and performance tracking for your entire team.",
    "landing.benefits.title": "Why Choose ServiScore?",
    "landing.benefits.subtitle": "We help businesses transform their service delivery from good to exceptional. Here's how we make a difference:",
    "landing.benefits.satisfaction": "Boost customer satisfaction scores by up to 40%",
    "landing.benefits.response": "Reduce response times with automated workflows",
    "landing.benefits.bottlenecks": "Identify service bottlenecks before they become problems",
    "landing.benefits.empower": "Empower your team with actionable performance data",
    "landing.benefits.integrate": "Seamlessly integrate with your existing tools",
    "landing.benefits.scale": "Scale your operations without compromising quality",
    "landing.benefits.satisfactionRate": "Customer Satisfaction Rate",
    "landing.benefits.averageScore": "Average score across all ServiScore partners",
    "landing.testimonials.title": "Trusted by Industry Leaders",
    "landing.testimonials.subtitle": "See what our customers have to say about their experience with ServiScore.",
    "landing.cta.title": "Start Improving Your Service Scores Today!",
    "landing.cta.subtitle": "Join thousands of businesses that trust ServiScore to deliver exceptional customer experiences.",
    "landing.cta.getStarted": "Get Started Now",
    "landing.cta.requestDemo": "Request Demo",
    "authForm.signIn": "Sign In",
    "authForm.signUp": "Sign Up",
    "authForm.signInSubtitle": "Enter your email and password to sign in!",
    "authForm.signUpSubtitle": "Enter your email and password to sign up!",
    "authForm.signInWith": "Sign in with",
    "authForm.signUpWith": "Sign up with",
    "authForm.or": "Or",
    "authForm.enterPassword": "Enter your password",
    "authForm.enterEmail": "Enter your email",
    "authForm.enterFirstName": "Enter your first name",
    "authForm.enterLastName": "Enter your last name",
    "authForm.keepLoggedIn": "Keep me logged in",
    "authForm.resetPassword": "Forgot password?",
    "authForm.dontHaveAccount": "Don't have an account?",
    "authForm.alreadyHaveAccount": "Already have an account?",
    "authForm.byCreating": "By creating an account means you agree to the",
    "authForm.termsConditions": "Terms and Conditions,",
    "authForm.and": "and our",
    "authForm.privacyPolicy": "Privacy Policy",
    "authForm.backToDashboard": "Back to dashboard",
    "sidebar.platform": "Platform",
    "sidebar.home": "Home",
    "sidebar.dashboard": "Dashboard",
    "sidebar.profile": "Profile",
    "sidebar.management": "Management",
    "sidebar.manageShops": "Manage Shops",
    "sidebar.manageServices": "Manage Services",
    "sidebar.team": "Team",
    "sidebar.analytics": "Analytics",
    "sidebar.shopAnalytics": "Shop Analytics",
    "sidebar.shopMetrics": "Shop Metrics",
    "sidebar.serviceMetrics": "Service Metrics",
    "sidebar.systemLogs": "System Logs",
    "sidebar.explore": "Explore",
    "sidebar.browseStores": "Browse Stores",
    "sidebar.browseServices": "Browse Services",
    "sidebar.admin": "Admin",
    "sidebar.superProfile": "Super Profile",
    "sidebar.settings": "Settings",
    "sidebar.getHelp": "Get Help",
    "sidebar.search": "Search",
    "about.title": "Built for",
    "about.titleHighlight": "Growth",
    "about.subtitle": "Everything you need to manage, scale, and succeed in one powerful platform.",
    "about.globalReach": "Global Reach",
    "about.globalReachDesc": "Expand your business beyond borders with our integrated SEO and localization tools.",
    "about.advancedAnalytics": "Advanced Analytics",
    "about.advancedAnalyticsDesc": "Gain deep insights into your audience and performance with real-time data visualization.",
    "about.designIntelligence": "Design Intelligence",
    "about.designIntelligenceDesc": "Create stunning, professional visuals effortlessly with our AI-powered design assistant.",
    "about.secureReliable": "Secure & Reliable",
    "about.secureReliableDesc": "Rest easy knowing your data and your customers' information are protected by enterprise-grade security.",
    "about.communityDriven": "Community Driven",
    "about.communityDrivenDesc": "Connect with a vibrant network of professionals and customers in your local area.",
    "about.lightningFast": "Lightning Fast",
    "about.lightningFastDesc": "Experience optimized performance that keeps your customers engaged and converting.",
    "footer.description": "Empowering local businesses and connecting communities through innovative digital solutions.",
    "footer.createdBy": "Created by passionate Riwi team",
    "footer.platform": "Platform",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.aboutUs": "About Us",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfService": "Terms of Service",
    "footer.cookiePolicy": "Cookie Policy",
    "footer.allRightsReserved": "All rights reserved.",
    "support.title": "Hi, how can we help?",
    "support.searchPlaceholder": "Search for articles",
    "support.exploreTopics": "Explore all topics",
    "support.sendingMoney": "Sending money",
    "support.sendingMoneyDesc": "Setting up, paying for, editing, and cancelling transfers.",
    "support.managingAccount": "Managing your account",
    "support.managingAccountDesc": "Setting up your account and getting verified.",
    "support.holdingMoney": "Holding money",
    "support.holdingMoneyDesc": "Holding balances, setting up Direct Debits, and using Interest & Stocks.",
    "support.wiseCard": "Wise card",
    "support.wiseCardDesc": "Ordering, activating, spending, and troubleshooting.",
    "support.receivingMoney": "Receiving money",
    "support.receivingMoneyDesc": "Using your account details to receive money.",
    "support.wiseBusiness": "Wise Business",
    "support.wiseBusinessDesc": "Multi-user access, accounting and using our API.",
    "support.stillNeedHelp": "Still need help?",
    "support.contactUs": "Contact us",
  },
  es: {
    "nav.home": "Inicio",
    "nav.services": "Servicios",
    "nav.profile": "Perfil",
    "nav.login": "Iniciar Sesión",
    "home.hero.title": "Descubre y Conecta",
    "home.hero.subtitle":
      "Tu centro comunitario para encontrar los mejores negocios locales y conectar con vecinos talentosos.",
    "home.services.title": "Servicios Comunitarios",
    "services.title": "Servicios Comunitarios",
    "services.subtitle": "Encuentra ayuda u ofrece tus habilidades a tus vecinos.",
    "services.filter": "Filtrar",
    "services.fixedPrice": "Precio fijo",
    "services.status.open": "Abierto",
    "services.post.button": "Publicar servicio",
    "services.post.title": "Publicar un servicio",
    "services.post.description": "Ofrece tus habilidades a la comunidad. Completa los detalles a continuación.",
    "services.post.serviceTitle": "Título del servicio",
    "services.post.serviceTitlePlaceholder": "Ej. Paseo de perros, Limpieza del hogar",
    "services.post.category": "Categoría",
    "services.post.categoryPlaceholder": "Seleccionar",
    "services.post.category.home": "Hogar",
    "services.post.category.pets": "Mascotas",
    "services.post.category.tech": "Tecnología",
    "services.post.category.education": "Educación",
    "services.post.price": "Precio ($)",
    "services.post.location": "Ubicación",
    "services.post.locationPlaceholder": "Ej. Centro, Zona oeste",
    "services.post.descriptionLabel": "Descripción",
    "services.post.descriptionPlaceholder": "Describe lo que ofreces...",
    "home.reviews": "reseñas",
    "service.back": "Volver a Servicios",
    "service.posted": "Publicado el",
    "service.description": "Descripción",
    "service.applicants": "Solicitantes",
    "service.noApplicants": "Aún no hay solicitantes.",
    "service.memberSince": "Miembro desde",
    "service.rating": "Calif.",
    "service.jobs": "Trabajos",
    "service.viewProfile": "Ver Perfil",
    "service.interested": "¿Interesado?",
    "service.applyHelp": "Aplica ahora para ayudar a {name} con esta tarea.",
    "service.applied": "Aplicado",
    "service.apply": "Aplicar al Servicio",
    "service.accept": "Aceptar",
    "service.decline": "Rechazar",
    "service.notFound": "Servicio no encontrado",
    "profile.settings": "Ajustes",
    "profile.logout": "Cerrar Sesión",
    "profile.completed": "Completados",
    "profile.publishedServices": "Servicios Publicados",
    "profile.noServices": "Aún no hay servicios publicados.",
    "profile.recentActivity": "Actividad Reciente",
    "profile.manage": "Gestionar",
    "profile.active": "Activo",
    "common.location": "Ubicación",
    "common.hours": "Horario",
    "common.about": "Sobre nosotros",
    "common.loading": "Cargando...",
    "auth.welcome": "Bienvenido de nuevo",
    "auth.login.subtitle": "Por favor ingrese sus detalles para iniciar sesión.",
    "auth.createAccount": "Crear una cuenta",
    "auth.register.subtitle": "¿Ya tienes una cuenta?",
    "auth.login": "Iniciar sesión",
    "auth.signup": "Registrarse",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.firstName": "Nombre",
    "auth.lastName": "Apellido",
    "auth.rememberMe": "Recuérdame",
    "auth.forgotPassword": "¿Olvidaste tu contraseña?",
    "auth.orLogin": "O iniciar sesión con",
    "auth.orRegister": "O registrarse con",
    "auth.agree": "Acepto los",
    "auth.terms": "Términos y Condiciones",
    "auth.google": "Google",
    "auth.apple": "Apple",
    "auth.overlay.title": "Capturando Momentos, Creando Recuerdos",
    "auth.overlay.subtitle": "Comienza tu viaje con nosotros hoy.",
    "auth.backToWebsite": "Volver al sitio web",
    "dashboard.title": "Panel de Control",
    "dashboard.welcome": "¡Bienvenido de nuevo! Aquí está el resumen de tu negocio.",
    "dashboard.newStore": "Nueva Tienda",
    "dashboard.newService": "Nuevo Servicio",
    "dashboard.totalStores": "Tiendas Totales",
    "dashboard.activeServices": "Servicios Activos",
    "dashboard.totalRevenue": "Ingresos Totales",
    "dashboard.totalCustomers": "Clientes Totales",
    "dashboard.fromLastMonth": "del mes pasado",
    "dashboard.recentActivity": "Actividad Reciente",
    "dashboard.recentActivityDesc": "Últimas actualizaciones de tus tiendas y servicios",
    "dashboard.topPerformers": "Mejores Desempeños",
    "dashboard.topPerformersDesc": "Tiendas con mejor desempeño este mes",
    "dashboard.newOrderReceived": "Nuevo pedido recibido",
    "dashboard.serviceCompleted": "Servicio completado",
    "dashboard.newReviewPosted": "Nueva reseña publicada",
    "dashboard.inventoryUpdated": "Inventario actualizado",
    "dashboard.revenue": "ingresos",
    "landing.hero.subtitle": "Bienvenido al futuro del servicio",
    "landing.hero.description": "Conecta, colabora y crece con ServiScore. Proporcionamos las herramientas que necesitas para elevar tu negocio y alcanzar a tu comunidad de manera efectiva.",
    "landing.hero.getStarted": "Comenzar",
    "landing.hero.learnMore": "Saber Más",
    "landing.features.title": "Características Clave",
    "landing.features.subtitle": "Todo lo que necesitas para elevar la calidad de tu servicio y la satisfacción del cliente.",
    "landing.features.chatbot": "Integración de Chatbot",
    "landing.features.chatbotDesc": "Automatiza el soporte al cliente con nuestro chatbot inteligente que maneja consultas comunes 24/7.",
    "landing.features.analytics": "Panel de Análisis",
    "landing.features.analyticsDesc": "Obtén información profunda sobre el rendimiento de tu servicio con métricas en tiempo real e informes visuales.",
    "landing.features.ui": "Interfaz Amigable",
    "landing.features.uiDesc": "Diseño intuitivo que no requiere capacitación. Pon a tu equipo en marcha en minutos.",
    "landing.features.feedback": "Retroalimentación Instantánea",
    "landing.features.feedbackDesc": "Recopila y analiza comentarios de clientes inmediatamente después de completar el servicio.",
    "landing.features.security": "Datos Seguros",
    "landing.features.securityDesc": "Seguridad de nivel empresarial para mantener los datos de tus clientes y negocio seguros y conformes.",
    "landing.features.team": "Gestión de Equipo",
    "landing.features.teamDesc": "Administra fácilmente roles, permisos y seguimiento del desempeño de todo tu equipo.",
    "landing.benefits.title": "¿Por Qué Elegir ServiScore?",
    "landing.benefits.subtitle": "Ayudamos a las empresas a transformar su prestación de servicios de buena a excepcional. Así es como marcamos la diferencia:",
    "landing.benefits.satisfaction": "Aumenta las puntuaciones de satisfacción del cliente hasta un 40%",
    "landing.benefits.response": "Reduce los tiempos de respuesta con flujos de trabajo automatizados",
    "landing.benefits.bottlenecks": "Identifica cuellos de botella en el servicio antes de que se conviertan en problemas",
    "landing.benefits.empower": "Empodera a tu equipo con datos de desempeño accionables",
    "landing.benefits.integrate": "Integra perfectamente con tus herramientas existentes",
    "landing.benefits.scale": "Escala tus operaciones sin comprometer la calidad",
    "landing.benefits.satisfactionRate": "Tasa de Satisfacción del Cliente",
    "landing.benefits.averageScore": "Puntuación promedio en todos los socios de ServiScore",
    "landing.testimonials.title": "Confiado por Líderes de la Industria",
    "landing.testimonials.subtitle": "Mira lo que nuestros clientes tienen que decir sobre su experiencia con ServiScore.",
    "landing.cta.title": "¡Comienza a Mejorar tus Puntuaciones de Servicio Hoy!",
    "landing.cta.subtitle": "Únete a miles de empresas que confían en ServiScore para brindar experiencias excepcionales a los clientes.",
    "landing.cta.getStarted": "Comenzar Ahora",
    "landing.cta.requestDemo": "Solicitar Demo",
    "authForm.signIn": "Iniciar Sesión",
    "authForm.signUp": "Registrarse",
    "authForm.signInSubtitle": "¡Ingresa tu correo y contraseña para iniciar sesión!",
    "authForm.signUpSubtitle": "¡Ingresa tu correo y contraseña para registrarte!",
    "authForm.signInWith": "Iniciar sesión con",
    "authForm.signUpWith": "Registrarse con",
    "authForm.or": "O",
    "authForm.enterPassword": "Ingresa tu contraseña",
    "authForm.enterEmail": "Ingresa tu correo",
    "authForm.enterFirstName": "Ingresa tu nombre",
    "authForm.enterLastName": "Ingresa tu apellido",
    "authForm.keepLoggedIn": "Mantenerme conectado",
    "authForm.resetPassword": "¿Olvidaste tu contraseña?",
    "authForm.dontHaveAccount": "¿No tienes una cuenta?",
    "authForm.alreadyHaveAccount": "¿Ya tienes una cuenta?",
    "authForm.byCreating": "Al crear una cuenta aceptas los",
    "authForm.termsConditions": "Términos y Condiciones,",
    "authForm.and": "y nuestra",
    "authForm.privacyPolicy": "Política de Privacidad",
    "authForm.backToDashboard": "Volver al panel",
    "sidebar.platform": "Plataforma",
    "sidebar.home": "Inicio",
    "sidebar.dashboard": "Panel",
    "sidebar.profile": "Perfil",
    "sidebar.management": "Gestión",
    "sidebar.manageShops": "Gestionar Tiendas",
    "sidebar.manageServices": "Gestionar Servicios",
    "sidebar.team": "Equipo",
    "sidebar.analytics": "Analíticas",
    "sidebar.shopAnalytics": "Análisis de Tiendas",
    "sidebar.shopMetrics": "Métricas de Tiendas",
    "sidebar.serviceMetrics": "Métricas de Servicios",
    "sidebar.systemLogs": "Registros del Sistema",
    "sidebar.explore": "Explorar",
    "sidebar.browseStores": "Explorar Tiendas",
    "sidebar.browseServices": "Explorar Servicios",
    "sidebar.admin": "Administrador",
    "sidebar.superProfile": "Super Perfil",
    "sidebar.settings": "Configuración",
    "sidebar.getHelp": "Obtener Ayuda",
    "sidebar.search": "Buscar",
    "about.title": "Construido para",
    "about.titleHighlight": "Crecer",
    "about.subtitle": "Todo lo que necesitas para gestionar, escalar y tener éxito en una poderosa plataforma.",
    "about.globalReach": "Alcance Global",
    "about.globalReachDesc": "Expande tu negocio más allá de las fronteras con nuestras herramientas integradas de SEO y localización.",
    "about.advancedAnalytics": "Análisis Avanzados",
    "about.advancedAnalyticsDesc": "Obtén información profunda sobre tu audiencia y rendimiento con visualización de datos en tiempo real.",
    "about.designIntelligence": "Inteligencia de Diseño",
    "about.designIntelligenceDesc": "Crea visuales impresionantes y profesionales sin esfuerzo con nuestro asistente de diseño impulsado por IA.",
    "about.secureReliable": "Seguro y Confiable",
    "about.secureReliableDesc": "Descansa tranquilo sabiendo que tus datos y la información de tus clientes están protegidos por seguridad de nivel empresarial.",
    "about.communityDriven": "Impulsado por la Comunidad",
    "about.communityDrivenDesc": "Conéctate con una red vibrante de profesionales y clientes en tu área local.",
    "about.lightningFast": "Súper Rápido",
    "about.lightningFastDesc": "Experimenta un rendimiento optimizado que mantiene a tus clientes comprometidos y convirtiendo.",
    "footer.description": "Empoderando negocios locales y conectando comunidades a través de soluciones digitales innovadoras.",
    "footer.createdBy": "Creado por equipo apasionado de Riwi",
    "footer.platform": "Plataforma",
    "footer.features": "Características",
    "footer.pricing": "Precios",
    "footer.aboutUs": "Sobre Nosotros",
    "footer.contact": "Contacto",
    "footer.legal": "Legal",
    "footer.privacyPolicy": "Política de Privacidad",
    "footer.termsOfService": "Términos de Servicio",
    "footer.cookiePolicy": "Política de Cookies",
    "footer.allRightsReserved": "Todos los derechos reservados.",
    "support.title": "Hola, ¿cómo podemos ayudarte?",
    "support.searchPlaceholder": "Buscar artículos",
    "support.exploreTopics": "Explorar todos los temas",
    "support.sendingMoney": "Enviar dinero",
    "support.sendingMoneyDesc": "Configuración, pago, edición y cancelación de transferencias.",
    "support.managingAccount": "Gestionar tu cuenta",
    "support.managingAccountDesc": "Configurar tu cuenta y verificarte.",
    "support.holdingMoney": "Mantener dinero",
    "support.holdingMoneyDesc": "Mantener saldos, configurar débitos directos y usar Intereses y Acciones.",
    "support.wiseCard": "Tarjeta Wise",
    "support.wiseCardDesc": "Pedido, activación, gasto y solución de problemas.",
    "support.receivingMoney": "Recibir dinero",
    "support.receivingMoneyDesc": "Usar los detalles de tu cuenta para recibir dinero.",
    "support.wiseBusiness": "Wise Business",
    "support.wiseBusinessDesc": "Acceso multiusuario, contabilidad y uso de nuestra API.",
    "support.stillNeedHelp": "¿Aún necesitas ayuda?",
    "support.contactUs": "Contáctanos",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en"
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY)
    return stored === "es" || stored === "en" ? stored : "en"
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, lang)
      window.dispatchEvent(new Event(LANGUAGE_EVENT_NAME))
    } catch {
      // ignore
    }
  }

  useEffect(() => {
    const handler = () => {
      try {
        const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY)
        if (stored === "es" || stored === "en") setLanguageState(stored)
      } catch {
        // ignore
      }
    }

    window.addEventListener(LANGUAGE_EVENT_NAME, handler)
    return () => window.removeEventListener(LANGUAGE_EVENT_NAME, handler)
  }, [])

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language][key] || key
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        text = text.replace(`{${paramKey}}`, String(value))
      })
    }
    return text
  }

  const value = useMemo(() => ({ language, setLanguage, t }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
